package Pojo;
// Generated 13.Kas.2019 19:50:41 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Users generated by hbm2java
 */
public class Users  extends DataType{


     private Integer id;
     private String userName;
     private String firstName;
     private String lastName;
     private String password;
     private byte[] image;
     private Set messagesForKimden = new HashSet(0);
     private Set messagesForKime = new HashSet(0);

    public Users() {
    }

	
    public Users(String userName, String firstName, String lastName, String password, byte[] image) {
        this.userName = userName;
        this.firstName = firstName;
        this.lastName = lastName;
        this.password = password;
        this.image = image;
    }
    public Users(String userName, String firstName, String lastName, String password, byte[] image, Set messagesForKimden, Set messagesForKime) {
       this.userName = userName;
       this.firstName = firstName;
       this.lastName = lastName;
       this.password = password;
       this.image = image;
       this.messagesForKimden = messagesForKimden;
       this.messagesForKime = messagesForKime;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public byte[] getImage() {
        return this.image;
    }
    
    public void setImage(byte[] image) {
        this.image = image;
    }
    public Set getMessagesForKimden() {
        return this.messagesForKimden;
    }
    
    public void setMessagesForKimden(Set messagesForKimden) {
        this.messagesForKimden = messagesForKimden;
    }
    public Set getMessagesForKime() {
        return this.messagesForKime;
    }
    
    public void setMessagesForKime(Set messagesForKime) {
        this.messagesForKime = messagesForKime;
    }




}


